# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exemplar}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dmitry Ratnikov"]
  s.date = %q{2010-08-16}
  s.email = %q{ratnikov@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "examples/algebra.rb",
     "exemplar.gemspec",
     "lib/exemplar.rb",
     "lib/exemplar/example.rb",
     "lib/exemplar/loggable.rb",
     "lib/exemplar/runner.rb",
     "test/example_test.rb",
     "test/runner_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/ratnikov/exemplar}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Makes writing examples easy and fun}
  s.test_files = [
    "test/example_test.rb",
     "test/runner_test.rb",
     "test/test_helper.rb",
     "examples/algebra.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

